import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { blog } from '../lib/blog';

export const GET: APIRoute = async () => {
  // Blog section: featured posts, generated by yamblog itself
  const blogSection = await blog.generateLlmsTxt();

  // Docs section: built from the docs collection's own frontmatter
  const docs = await getCollection('docs');
  const docsSection = [
    '## Docs',
    '',
    ...docs.map(
      (doc) =>
        `- [${doc.data.title}](https://yamblog.dev/${doc.id}/): ${doc.data.description ?? ''}`.trimEnd(),
    ),
  ].join('\n');

  const body = `# Yamblog

> File-based, type-safe, framework-agnostic markdown blog engine for Next.js, Astro, and React. Drop markdown files in a folder, get a fully typed blog with search, RSS, sitemap, and llms.txt generation.

Packages: @yamblog/core (engine), @yamblog/next, @yamblog/astro, @yamblog/react (adapters), @yamblog/remark (markdown plugins). Source: https://github.com/yamblog/yamblog

${docsSection}

${blogSection}
`;

  return new Response(body, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 's-maxage=3600, stale-while-revalidate',
    },
  });
};
